apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-nas
  labels:
    name: tv-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - noatime
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/media/TV"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-nas
  labels:
    name: movies-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - noatime
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/media/Movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies4k-nas
  labels:
    name: movies4k-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - noatime
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/media/4k/movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv4k-nas
  labels:
    name: tv4k-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - noatime
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/media/4k/tv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-nas
  labels:
    name: music-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - noatime
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/media/music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerdata
  labels:
    name: dockerdata-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - nfsvers=4.1
    - sync
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/dockerdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cameras-nas
  labels:
    name: cameras-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - nfsvers=4.1
    - sync
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/cameras"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-nas
  labels:
    name: images-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - sync
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/images"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-nas
  labels:
    name: backups-nas
spec:
  capacity:
    storage: 80Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - noexec
    - sync
    - nfsvers=4.1
  nfs:
    server: mediastore.home
    path: "/mnt/sirius/backups"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexmediaserver
  labels:
    name: plexmediaserver
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - soft
    - nfsvers=4.1
  nfs:
    server: plexmediaserver.home
    path: "/var/lib/plexmediaserver"
