apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        livenessProbe:
          httpGet:
            path: /status/200
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
          name: httpbin
