apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
  # annotations:
    # kube-router.io/service.dsr: "tunnel"
spec:
  ports:
  - name: httpbin
    port: 8080
    targetPort: httpbin
  selector:
    app: httpbin
