apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:

  nginx.conf: |
    user root;
    worker_processes 5;
    
    error_log /etc/nginx/logs/error.log crit;
    pid /var/run/nginx.pid;
    
    
    events {
    
        worker_connections 1024;
    }
    
    
    http {
    
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        client_body_temp_path /tmp 1 2;
    
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log /etc/nginx/logs/access.log main;
    
        #    sendfile       on;
        tcp_nopush on;
        tcp_nodelay on;
    
        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 180m;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    
        keepalive_timeout 65;
        gzip on;
        gzip_vary on;
        gzip_min_length 10240;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;
        gzip_disable "MSIE [1-6]\.";
    
        server {
    
            listen 80;
    
                    location = /ping {
                      add_header Content-Type text/plain;
                      return 200  'pong';
                    }
    
                    location / {
              return 301 https://$host$request_uri;
                    }
        }
        server {
    
            listen 443 ssl http2;
            #     listen 0.0.0.0:80;
    
            server_name plexrequest.me;
            access_log /etc/nginx/logs/nginx-access.log;
    
            ssl_certificate /etc/nginx/ssl/plexrequest.me.pem;
            #ssl_certificate          /etc/nginx/ssl/nginx-selfsigned.crt;
            ssl_certificate_key /etc/nginx/ssl/plexrequest.me.key;
            #ssl_certificate_key      /etc/nginx/ssl/nginx-selfsigned.key;
            #ssl_client_certificate /etc/nginx/ssl/cloudflare.crt;
            #ssl_verify_client on;
            ssl_verify_client off;
            #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            #ssl_prefer_server_ciphers on;
            #ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
    
                    location = /ping {
                      add_header Content-Type text/plain;
                      return 200  'pong';
                    }
    
    
            location / {
    
                proxy_pass http://192.168.1.18:3580;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300;
                proxy_redirect http://192.168.1.18:3580 https://$host;
            }
            location /nginx-status {
    
                stub_status on;
                access_log off;
                allow 192.168.1.0/24;
                allow 127.0.0.1;
                deny all;
            }
        }
    
        server {
    
            listen 443 ssl http2;
            server_name unifi.evanrichardsonphotography.com;
            access_log /etc/nginx/logs/nginx-access-unifi.log;
    
            ssl_certificate /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.crt;
            ssl_certificate_key /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.key;
            ssl_verify_client off;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_prefer_server_ciphers on;
            ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
    
            location / {
    
                proxy_pass https://192.168.1.18:8443;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_buffering off;
            }
        }
    
        server {
    
            listen 443 ssl http2;
            server_name security.evanrichardsonphotography.com;
            access_log /etc/nginx/logs/nginx-access-unifi.log;
    
            ssl_certificate /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.crt;
            ssl_certificate_key /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.key;
            ssl_verify_client off;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_prefer_server_ciphers on;
            ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
    
            location / {
    
                proxy_pass https://192.168.1.18:7443;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_buffering off;
            }
        }
    
        server {
    
            listen 443 ssl http2;
            server_name nms.evanrichardsonphotography.com;
            access_log /etc/nginx/logs/nginx-access-librenms.log;
    
            ssl_certificate /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.crt;
            ssl_certificate_key /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.key;
            ssl_verify_client off;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_prefer_server_ciphers on;
            ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
    
            location / {
    
                proxy_pass http://192.168.1.18:8668;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_buffering off;
                proxy_redirect http://192.168.1.18:8668 https://$host;
            }
        }
    
        server {
    
            listen 443 ssl http2;
            server_name cloud.evanrichardsonphotography.com;
            access_log /etc/nginx/logs/nginx-access-cloud.log;
            sendfile on;
            send_timeout 600s;
            client_body_in_file_only clean;
            client_body_buffer_size 32K;
    
            # set max upload size
            client_max_body_size 4000M;
    
    
            ssl_certificate /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.crt;
            ssl_certificate_key /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.key;
            ssl_verify_client off;
            #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            #ssl_prefer_server_ciphers on;
            #ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
    
            location / {
    
                proxy_set_header Host $host;
                            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                            proxy_set_header X-Real-IP $remote_addr;
                            proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering off;
                proxy_request_buffering off;
                            proxy_pass https://192.168.1.18:34443;
    
            }
        }
    
            server {
    
                    listen 443 ssl http2;
                    server_name plexstats.evanrichardsonphotography.com;
                    access_log /etc/nginx/logs/plexstats-access-cloud.log;
                    sendfile on;
                    send_timeout 600s;
                    client_body_in_file_only clean;
                    client_body_buffer_size 32K;
    
                    # set max upload size
                    client_max_body_size 4000M;
    
    
                    ssl_certificate /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.crt;
                    ssl_certificate_key /etc/nginx/ssl/star.evanrichardsonphotography.com-1-15-2018.key;
                    ssl_verify_client off;
                    #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                    #ssl_prefer_server_ciphers on;
                    #ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+AES128:!ADH:!AECDH:!MD5;
    
                    location / {
    
                            proxy_pass https://192.168.1.18:8181;
                            proxy_buffering off;
                            proxy_request_buffering off;
                            proxy_ssl_session_reuse off;
    
                    }
            }
    }
