apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deluge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deluge
    spec:
      volumes:
      - name:  dockerdata
        persistentVolumeClaim:
          claimName: dockerdata-nas
      - name: deluge-secrets
        secret:
          secretName: deluge
      containers:
      - name: deluge
        image: linuxserver/deluge:126
        volumeMounts:
        - name: dockerdata
          subPath: deluge/config
          mountPath: /config
        - name: dockerdata
          subPath: deluge/downloads
          mountPath: /downloads
        - name: dockerdata
          subPath: deluge/watch
          mountPath: /watch
          #        - name: deluge-secrets
          #subPath: auth
          #mountPath: /config
          #readOnly: true
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/Los_Angeles'
        ports:
        - containerPort: 8112
          name: deluge-webui
        - containerPort: 58846
          name: deluge-daemon
        - containerPort: 62957
          name: deluge-bt
        readinessProbe:
          tcpSocket:
            port: deluge-bt
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: deluge-bt
          initialDelaySeconds: 15
          periodSeconds: 20

