apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  selector:
    app: deluge
#  clusterIP: 10.100.2.94
  ports:
  - name: deluge
    port: 8112
    targetPort: 8112
  - name: deluge-daemon
    port: 58846
    targetPort: 58846
  - name: deluge-bt
    port: 62957
    targetPort: 62957
